apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: nginx-mra
    component: mysql
  namespace: nginx-mra
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    name: tcp
  selector:
    app: nginx-mra
    component: mysql
